Search.appendIndex(
    [
                {
            "fqsen": "\\Ren\\ServerTrait\\UnixServerTrait",
            "name": "UnixServerTrait",
            "summary": "",
            "url": "classes/Ren-ServerTrait-UnixServerTrait.html"
        },                {
            "fqsen": "\\Ren\\ServerTrait\\UnixServerTrait\u003A\u003Astart\u0028\u0029",
            "name": "start",
            "summary": "Starts\u0020new\u0020UnixServer",
            "url": "classes/Ren-ServerTrait-UnixServerTrait.html#method_start"
        },                {
            "fqsen": "\\Ren\\ServerTrait\\UnixServerTrait\u003A\u003A\u0024server",
            "name": "server",
            "summary": "UnixServer\u0020object",
            "url": "classes/Ren-ServerTrait-UnixServerTrait.html#property_server"
        },                {
            "fqsen": "\\Ren\\ServerTrait\\ServerInterface",
            "name": "ServerInterface",
            "summary": "",
            "url": "classes/Ren-ServerTrait-ServerInterface.html"
        },                {
            "fqsen": "\\Ren\\ServerTrait\\ServerInterface\u003A\u003AgetAddress\u0028\u0029",
            "name": "getAddress",
            "summary": "Returns\u0020server\u0020address",
            "url": "classes/Ren-ServerTrait-ServerInterface.html#method_getAddress"
        },                {
            "fqsen": "\\Ren\\ServerTrait\\ServerInterface\u003A\u003Apause\u0028\u0029",
            "name": "pause",
            "summary": "Pauses\u0020the\u0020server",
            "url": "classes/Ren-ServerTrait-ServerInterface.html#method_pause"
        },                {
            "fqsen": "\\Ren\\ServerTrait\\ServerInterface\u003A\u003Aresume\u0028\u0029",
            "name": "resume",
            "summary": "Resumes\u0020the\u0020server",
            "url": "classes/Ren-ServerTrait-ServerInterface.html#method_resume"
        },                {
            "fqsen": "\\Ren\\ServerTrait\\ServerInterface\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Closes\u0020the\u0020server",
            "url": "classes/Ren-ServerTrait-ServerInterface.html#method_close"
        },                {
            "fqsen": "\\Ren\\ServerTrait\\ServerInterface\u003A\u003AonConnection\u0028\u0029",
            "name": "onConnection",
            "summary": "Callback\u0020to\u0020be\u0020called\u0020on\u0020new\u0020connection",
            "url": "classes/Ren-ServerTrait-ServerInterface.html#method_onConnection"
        },                {
            "fqsen": "\\Ren\\ServerTrait\\ServerInterface\u003A\u003AonError\u0028\u0029",
            "name": "onError",
            "summary": "Callback\u0020to\u0020be\u0020called\u0020on\u0020error",
            "url": "classes/Ren-ServerTrait-ServerInterface.html#method_onError"
        },                {
            "fqsen": "\\Ren\\ServerTrait\\TCPServerTrait",
            "name": "TCPServerTrait",
            "summary": "",
            "url": "classes/Ren-ServerTrait-TCPServerTrait.html"
        },                {
            "fqsen": "\\Ren\\ServerTrait\\TCPServerTrait\u003A\u003Astart\u0028\u0029",
            "name": "start",
            "summary": "Starts\u0020new\u0020TcpServer",
            "url": "classes/Ren-ServerTrait-TCPServerTrait.html#method_start"
        },                {
            "fqsen": "\\Ren\\ServerTrait\\TCPServerTrait\u003A\u003A\u0024server",
            "name": "server",
            "summary": "TcpServer\u0020object",
            "url": "classes/Ren-ServerTrait-TCPServerTrait.html#property_server"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Ren\\ServerTrait",
            "name": "ServerTrait",
            "summary": "",
            "url": "namespaces/ren-servertrait.html"
        },                {
            "fqsen": "\\Ren",
            "name": "Ren",
            "summary": "",
            "url": "namespaces/ren.html"
        }            ]
);
